name: Pack Artifact

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  PackArtifact:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Pack Resdata
      run: |
        python pack_resdata.py
    - name: Upload
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "ResData"
        prerelease: true
        files: resdata.zip